# Basic and Principle

## Installations and Import

In [1]:
!pip install -q torchvision plotly tqdm

In [2]:
import torch
from torch import nn, optim
import torch.utils.data.dataloader as dataloader
from torchvision import datasets, transforms
import plotly.express as px
import pandas as pd

## Models

In [3]:
class Generator(nn.Module):
    def __init__(self, letant_dim: int, im_dim):
        super().__init__()
        self.im_dim = im_dim
        self.len_im = im_dim[0] * im_dim[1]
        self.letant_dim = letant_dim
        self.model = nn.Sequential(
            nn.Linear(letant_dim, 256),
            nn.LeakyReLU(),
            nn.Linear(256, self.len_im),
            nn.Tanh(),
        )

    def forward(self, X):
        return self.model(X.view((-1, self.letant_dim))).view((-1, *self.im_dim))


class Discrimnator(nn.Module):
    def __init__(self, im_dim) -> None:
        super().__init__()
        self.im_dim = im_dim
        self.len_im = im_dim[0] * im_dim[1]
        self.model = nn.Sequential(
            nn.Linear(self.len_im, 128), nn.LeakyReLU(), nn.Linear(128, 1), nn.Sigmoid()
        )

    def forward(self, X):
        return self.model(X.view(-1, self.len_im)).view(-1)

In [ ]:
transfomer = transforms.Compose([transforms.ToTensor(), transforms.Normalize(0.5, 0.5)])
mnist_data = datasets.MNIST("/dataset", download=True, transform=transfomer)

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
letant_dim = 100
im_dim = (28, 28)
generator = Generator(letant_dim, im_dim).to(device)
discrimnator = Discrimnator(im_dim).to(device)

In [7]:
lr = 3e-4
optim_g = optim.Adam(generator.parameters(), lr=lr)
optim_d = optim.Adam(discrimnator.parameters(), lr=lr)
loss_f = nn.BCELoss()

In [8]:
from math import ceil

num_epochs = 32
batch_size = 64
out_data = pd.DataFrame(
    {"epoch": pd.NA, "batch": pd.NA, "loss_g": pd.NA, "loss_d": pd.NA},
    index=range(num_epochs * ceil(len(mnist_data) / batch_size)),
)

In [9]:
from IPython.display import clear_output

ind_out_data = 0
for epoch_ind in range(num_epochs):
    loader = dataloader.DataLoader(mnist_data, batch_size=batch_size, shuffle=True)
    for i_batch, (X, _) in enumerate(loader):
        optim_g.zero_grad()
        optim_d.zero_grad()
        noise = torch.rand(X.shape[0], letant_dim).to(device)
        fake = generator(noise)
        loss_d_fake = loss_f(discrimnator(fake), torch.zeros(fake.shape[0]).to(device))
        loss_d_real = loss_f(
            discrimnator(X.to(device)), torch.ones(X.shape[0]).to(device)
        )
        loss_d = (loss_d_fake + loss_d_real) / 2
        loss_d.backward(retain_graph=True)
        optim_d.step()

        loss_g = loss_f(discrimnator(fake), torch.ones(fake.shape[0]).to(device))
        loss_g.backward()
        optim_g.step()
        out_data.loc[ind_out_data] = [epoch_ind, i_batch, loss_g.item(), loss_d.item()]
        ind_out_data += 1
    with torch.no_grad():
        noise = torch.rand(10, letant_dim)
        im = generator(noise.to(device))
        clear_output(wait=True)
        px.imshow(im.cpu().detach(), facet_col=0, facet_col_wrap=5).show()
        px.line(out_data, x="batch", y="loss_g", color="epoch").show()

KeyboardInterrupt: 

In [ ]:
from math import ceil
from IPython.display import clear_output

num_epochs = 20
batch_size = 32
out_data = pd.DataFrame(
    {"epochs": pd.NA, "batch": pd.NA, "loss_g": pd.NA, "loss_d": pd.NA},
    index=range(num_epochs * ceil(len(mnist_data) / batch_size)),
)
index_data = 0
for epoch in range(num_epochs):
    loader = dataloader.DataLoader(mnist_data, batch_size=batch_size, shuffle=True)
    for batch_i, (X, _) in enumerate(loader):
        curr_batch_size = X.shape[0]

        ### Train Discriminator: max log(D(x)) + log(1 - D(G(z)))
        noise = torch.randn(curr_batch_size, letant_dim).to(device)
        fake = generator(noise)
        disc_real = discrimnator(X.to(device)).view(-1)
        lossD_real = loss_f(disc_real, torch.ones_like(disc_real).to(device))
        disc_fake = discrimnator(fake).view(-1)
        lossD_fake = loss_f(disc_fake, torch.zeros_like(disc_fake).to(device))
        lossD = (lossD_real + lossD_fake) / 2
        optim_d.zero_grad()
        lossD.backward(retain_graph=True)
        optim_d.step()

        ### Train Generator: min log(1 - D(G(z))) <-> max log(D(G(z))
        # where the second option of maximizing doesn't suffer from
        # saturating gradients
        output = discrimnator(fake).view(-1)
        lossG = loss_f(output, torch.ones_like(output).to(device))
        optim_g.zero_grad()
        lossG.backward()
        optim_g.step()

        out_data.loc[index_data] = [epoch, batch_i, lossG.item(), lossD.item()]
        index_data += 1

    with torch.no_grad():
        fake = generator(torch.rand(10, 100).to(device))
        clear_output(wait=True)
        px.imshow(fake.cpu().detach(), facet_col=0, facet_col_wrap=5).show()
        px.line(out_data, x="batch", y=["loss_g"], color="epochs").show()

In [ ]:
!pip install -q torchvision plotly black[jupyter] tqdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 23.2 MB/s eta 0:00:00


In [ ]:
import torch
from torch import nn, optim
from torch.utils.data import dataloader
from torchvision import transforms, datasets
from plotly import express as px, graph_objects as go
import pandas as pd
import numpy as np
import os

In [ ]:
# from google.colab import drive

# drive.mount("/content/drive")

In [ ]:
# !black '/content/drive/MyDrive/gan_for_Day/chang_train_ratio_6/update_in_run_time_6.ipynb'
# !black '/content/drive/MyDrive/Colab Notebooks/gan_for_Day/chang_train_ratio_6/update_in_run_time_6.ipynb'

In [ ]:
from typing import Tuple, List

ImageDimType = Tuple[int, int]
ImageType = torch.Tensor
TensorType = torch.Tensor
DataSetVisionType = datasets.vision.VisionDataset
LossFunctionType = nn.modules.loss._WeightedLoss
OptimizerType = optim.Optimizer
DeviceType = str

<div dir="rtl" lang="he" xml:lang="he">

## יצירת הדטה

In [ ]:
f = lambda x:  x**2 + 10
X = (torch.randn(1000)-0.5)*10
y = f(X)
Xy = torch.stack([X,y]) # 2x1000,on the first row is X, on the second row is y
data = Xy.T             # 1000x2, every row is a sample
px.scatter(x=Xy[0],y=Xy[1]).show()



<div dir="rtl" lang="he" xml:lang="he">

## יצירת המודלים


In [ ]:
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 16),
            nn.LeakyReLU(),
            nn.Linear(16, 32),
            nn.LeakyReLU(),
            nn.Linear(32, 2),
        )
    def forward(self, x):
        return self.model(x)




In [ ]:
px.scatter(*Generator()(torch.randn(10000, 2)).detach().T)

In [ ]:
class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 16),
            nn.Dropout(0.2),
            nn.LeakyReLU(),
            nn.Linear(16, 16),
            nn.Dropout(0.2),
            nn.LeakyReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid(),
        )
    def forward(self, x):
        return self.model(x)

In [ ]:
Discriminator()(torch.randn(10,2))

tensor([[0.5971],
        [0.5437],
        [0.5894],
        [0.6706],
        [0.5888],
        [0.6157],
        [0.5779],
        [0.5747],
        [0.5978],
        [0.6543]], grad_fn=<SigmoidBackward0>)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
discriminator = Discriminator().to(device)
generator = Generator().to(device)
optim_d = optim.Adam(Discriminator().parameters())
optim_g = optim.Adam(Generator().parameters())
loss_fn = nn.BCELoss()

<div dir="rtl" lang="he" xml:lang="he">

## אימון

In [ ]:
from math import ceil
epochs = 300
batch_size = 64
num_batch = ceil(len(data)/batch_size)
record_data = pd.DataFrame(
    {"epoch": int(), "batch": int(), "loss_d": float(), "loss_g": float()},
    index=range(epochs * num_batch),
)
example_gen = torch.empty(epochs,10,2)

In [ ]:
run_ind = 0
from tqdm.notebook import tqdm
from IPython.display import clear_output

for epoch in range(epochs):
    data_loader = dataloader.DataLoader(data, batch_size=batch_size, shuffle=True)
    for batch_ind, points in enumerate(data_loader):
        points = points.to(device)
        # Train discriminator
        optim_d.zero_grad()
        fake = generator(torch.randn(len(points), 2, device=device))
        loss_d = loss_fn(
            discriminator(points), torch.ones(len(points),1, device=device)
        )
        loss_d += loss_fn(
            discriminator(fake), torch.zeros(len(points),1, device=device)
        )
        loss_d.backward(retain_graph=True)
        optim_d.step()
        # Train generator
        optim_g.zero_grad()
        fake = generator(torch.randn(len(points), 2, device=device))
        loss_g = loss_fn(discriminator(fake), torch.ones(len(points),1, device=device))
        loss_g.backward()
        optim_g.step()
        # Record losses
        record_data.iloc[run_ind] = epoch, batch_ind, loss_d.item(), loss_g.item()
        run_ind += 1
    clear_output(wait=True)
    with torch.no_grad():
        example_gen[epoch] = generator(torch.rand(10,2,device=device)).detach().cpu()
px.line(
    record_data, x="batch", y=["loss_d", "loss_g"], animation_frame="epoch"
).show()


In [ ]:
example_gen = example_gen.transpose(2,1)

In [ ]:
# @title { run: "auto" }
ind = 279 # @param {type:"slider", min:0, max:299, step:1}
px.scatter(x=example_gen[ind,0],y=example_gen[ind,1]).show()

In [ ]:
px.scatter(example_gen)


ValueError: Must pass 2-d input. shape=(300, 2, 10)

In [ ]:
import random

var, mean = random.randint(0, 10), random.randint(0, 10)
p_real = (torch.randn(10000) * var + mean).reshape(-1, 1)
bin_centers, bin_count = torch.histogram(p_real, bins=30, density=True)
fig = go.Figure(
    data=[
        go.Scatter(
            x=bin_count,
            y=bin_centers,
            mode="lines",
        )
    ]
)
fig.show()

In [ ]:
class D(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(1, 2),
            nn.Tanh(),
            nn.Linear(2, 1),
            nn.Sigmoid(),
        )
    def forward(self, x):
        return self.model(x)
class G(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(1, 1),
            nn.Tanh(),
            nn.Linear(1, 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        return self.model(x)
line = torch.linspace(-10,10,10).reshape(-1,1)
print(G()(line))
print(D()(line))

tensor([[0.4580],
        [0.4580],
        [0.4581],
        [0.4590],
        [0.4711],
        [0.5180],
        [0.5354],
        [0.5369],
        [0.5370],
        [0.5370]], grad_fn=<SigmoidBackward0>)
tensor([[0.7132],
        [0.7132],
        [0.7130],
        [0.7077],
        [0.6197],
        [0.2787],
        [0.2335],
        [0.2325],
        [0.2325],
        [0.2325]], grad_fn=<SigmoidBackward0>)


In [ ]:
go.Figure(
    data=[
        go.Scatter(
            x=line.flatten(),
            y=G()(line).detach().flatten(),
            mode="lines",
        )
    ]
).show()

In [ ]:
next(iter(dataloader.DataLoader(p_real, batch_size=10, shuffle=True)))

tensor([[6.],
        [6.],
        [6.],
        [6.],
        [6.],
        [6.],
        [6.],
        [6.],
        [6.],
        [6.]])

In [ ]:
line_space = torch.linspace(-10, 10, 1000).reshape(-1, 1)
fig = go.Figure(
    data=[
        go.Scatter(
            x=line_space.flatten(),
            y=D()(line_space).detach().flatten(),
            mode="lines",
            name="discriminator",
        ),
        go.Scatter(
            x=line_space.flatten(),
            y=G()(line_space).detach().flatten(),
            mode="lines",
            name="generator",
        ),
        go.Scatter(x=bin_count, y=bin_centers, mode="lines", name="real"),
    ]
).show()

<div dir="rtl" lang="he" xml:lang="he">

## פונקצייות

<div dir="rtl" lang="he" xml:lang="he">

##הרצה

In [ ]:
from math import ceil
device = "cuda" if torch.cuda.is_available() else "cpu"
epochs = 100
batch_size = 64
num_batch = ceil(len(p_real) / batch_size) * epochs
record_data = pd.DataFrame(
    {"epoch": int(), "batch": int(), "loss_d": float(), "loss_g": float()},
    index=range(num_batch),
)
example_gen = torch.empty(epochs, 100, 1)
generator = G().to(device)
discriminator = D().to(device)
optim_d = optim.Adam(D().parameters())
optim_g = optim.Adam(G().parameters())
loss_fn = nn.BCELoss()


In [ ]:
run_ind = 0
from tqdm.notebook import tqdm
from IPython.display import clear_output

for epoch in tqdm(range(epochs)):
    data_loader = dataloader.DataLoader(p_real, batch_size=batch_size, shuffle=True)
    for batch_ind, points in enumerate(data_loader):
        points = points.to(device)
        # Train discriminator
        optim_d.zero_grad()
        fake = generator(torch.randn(len(points), 1, device=device))
        loss_d = loss_fn(
            discriminator(points), torch.ones(len(points), 1, device=device)
        )
        loss_d += loss_fn(
            discriminator(fake), torch.zeros(len(points), 1, device=device)
        )
        loss_d = loss_d / 2
        loss_d.backward(retain_graph=True)
        optim_d.step()
        # Train generator
        optim_g.zero_grad()
        fake = generator(torch.randn(len(points), 1, device=device))
        loss_g = loss_fn(discriminator(fake), torch.ones(len(points), 1, device=device))
        loss_g.backward()
        optim_g.step()
        # Record losses
        record_data.iloc[run_ind] = epoch, batch_ind, loss_d.item(), loss_g.item()
        run_ind += 1
    # clear_output(wait=True)
    # with torch.no_grad():
    #     example_gen[epoch] = generator(torch.rand(100, 1, device=device)).detach().cpu()
    #     px.line(
    #         record_data, x="batch", y=["loss_d", "loss_g"], animation_frame="epoch"
    #     ).show()
    #     px.histogram(example_gen[epoch], marginal="rug").show()

  0%|          | 0/100 [00:00<?, ?it/s]

In [ ]:
line_space = torch.linspace(-10, 10, 1000).reshape(-1, 1)
fig = go.Figure(
    data=[
        go.Scatter(
            x=line_space.flatten(),
            y=discriminator(line_space).detach().flatten(),
            mode="lines",
            name="discriminator",
        ),
        go.Scatter(
            x=line_space.flatten(),
            y=generator(line_space).detach().flatten(),
            mode="lines",
            name="generator",
        ),
        go.Scatter(x=bin_count, y=bin_centers, mode="lines", name="real"),
    ]
).show()